steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=msommii'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyB0zPzaidQLDpNyrh7ReaiRyNhp8HOAPfc'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=msommii.firebaseapp.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=msommii.firebasestorage.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=pk_test_3531fac258f9e1e40a92e942e313e046fbf49866'
      - '--build-arg'
      - 'PAYSTACK_SECRET_KEY=sk_test_caf341ef6d5594a1069c7f9c9465fb2124150e07'
      - '--build-arg'
      - 'NEXT_PUBLIC_APP_URL=https://sales-uurxypxfoa-uc.a.run.app'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:${BUILD_ID}'
      - '.'

  # 2. Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:${BUILD_ID}']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:${BUILD_ID}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--project'
      - '${_PROJECT_ID}'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=msommii,NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyB0zPzaidQLDpNyrh7ReaiRyNhp8HOAPfc,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=msommii.firebaseapp.com,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=msommii.firebasestorage.app,NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=pk_test_3531fac258f9e1e40a92e942e313e046fbf49866,PAYSTACK_SECRET_KEY=sk_test_caf341ef6d5594a1069c7f9c9465fb2124150e07,NEXT_PUBLIC_APP_URL=https://sales-uurxypxfoa-uc.a.run.app,APP_URL=https://sales-uurxypxfoa-uc.a.run.app,FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@msommii.iam.gserviceaccount.com,EMAIL_HOST=smtp.gmail.com,EMAIL_PORT=587,EMAIL_USER=hi@kss.or.ke,EMAIL_PASSWORD=yvva uynv aqry kdmi,EMAIL_FROM_NAME=KSS Academy,FIREBASE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwGXzvuNXDZHQh
aZEH/Uj/opkWlYx5Xm+IitnhgPnsqmHHBi/PL4V2fSOQ3lK1B6zAadwsRA+t4/g3
UlEvVBbJX/xMPnicAvtOGT9hv9t/NfQ8GC18i8G82yBuNXXL7NbbEtP/glPSw+sf
OX0b9bUMiV39ju6QUWvJFSl5ibOVd6lWWxFXB9xmVeWn+keodw6rLQTWa1Rj95pW
UMaC9ev/Y6V9ANcGoToNOamJ5U33eG//5b+GwT8dvvqR/fvyOunGWq7P9yfYW9id
+kyAyRlJQBcv5GUUPx+vrMKNcR/fqYxIX7w+uz+RDqL3ce4+zIt59omsvUB3ivBb
V2oRV68XAgMBAAECggEAAPjluDBwjwdxyVzFrgzHcjs0a4FViQwCQ0zk9A+cEaLv
2ZiepfRbYR1CwizVZGYk8tutbq8iLlxuWpEr8pNycW0uvZWwtnJ2bxFznfdgX7JC
usbgEBUjc4alhgY/NBTcK3x4oCtY3svcc0vZdXs5+IDqUcPlbErkH0mXH4fTmSp8
HBnbnpNYil+UEQdRlueac6eOB2o/DDiaB70hw4Vqm1fwzTRkc8S6zvQDJ5RiEwS6
1Pwi0pSl3Ur9AZr9kLoBt0plN5ZMOJtokKdnVpJDMWJeMqPELz/qOyZcTC07HxuY
eii+frTnTCbIWTS1qkkfoPfT1YMrbx96RbRKLwzYAQKBgQDph7676LJ++Mbnypsz
Yhf9oqGmA1Eljqv5bY1ZvMc6o8iba4zT0uOicGeRk4lvBiOvACdFAg8rbAQ7Cclv
ktbMw4Alir8vL3yOfH5tzXKY6f5zeDzj/tY80DUD2lg0vynr3+lBCaLmMyucXmlo
3JamTM8QOLhBdtSKxelt7JI3FwKBgQDBCyAgxMq6qfdkQoIinujHRSZNgxO5SsED
1l8TKoVj0dgEqLkAYE2EBtZ/jBaLSmE9uOXhqUVlN6utxyz/qSgiOZtToU1VDos1
zgUh0EZHE/tNZV92da2lZEvqqBxc6fwWf+PM12wRZdk9FYN7mYuuoijpWk+O5D0i
H7QbgVFIAQKBgDk84zvtUeqbES141Edo0JaDCPnGsFnzOSV+e3m2MmKmCCJH3xGA
C/khcdEVh0bmC1L2R6m7UnqDFBpgULX/GJTBiiQpeKiZC/9kdhx1kZP3Lj2hB9Od
/2aSZZwXJS1weVbt357oPLwNaK//1/gysN37z3ibXlX1SSzmS0t9A21rAoGAVFTd
5jLSNZWGw7/iRemR22uz/eyjMzEa/OgrhJ3ww9iqO+7RUv6/Hhw2bGXwe001Cde6
ZUijTkJxt2rpl454P+tWlcRDmkLOQeUMjOcFrItoHzmH6KIkB7q3B34FVfnJ7LJV
++ioBzmtG2hIljhPsyyYHskbNFs08bFT5ygpMAECgYEA6IfnweahRvu2GmRGQMK4
xBaK0c9kyy1G+5+3w/j2f43oVTRlfKmIlo6Ck7OybUQs9XCbmmUWMuw+QITYHSRN
ztWA+RpIJxzgR7NWvWJ0PvyRCbSZwjMkDfhehwXMTgXzoovPvbTZN4kTEPnN6iLs
Ijj45fnXFhqmYPpD9tG0MWc=
-----END PRIVATE KEY-----'

substitutions:
  _PROJECT_ID: gonogasport
  _SERVICE_NAME: sales
  _REGION: us-central1

images:
  - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:${BUILD_ID}'

options:
  logging: CLOUD_LOGGING_ONLY
