'use client';
import { useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, Save, RefreshCw, Plus, Trash2, Monitor, MapPin, Laptop, Video, FileText, X, ChevronDown, ChevronUp } from "lucide-react";
import { useUsersFirestore, useCollection, useUser } from '@/firebase';
import { collection, query, where } from 'firebase/firestore';
import type { Cohort } from '@/lib/cohort-types';
import type { Program } from '@/lib/program-types';
import type { User } from '@/lib/user-types';
import type { ContentItem } from '@/lib/content-library-types';
import type { DeliveryType, TimingType } from '@/lib/learning-types';
import { createLearningCourse, createLearningUnit } from '@/lib/learning';
import Link from 'next/link';

// Module data structure for inline creation
interface ModuleDraft {
    id: string; // Temp client-side ID
    title: string;
    description: string;
    moduleNumber: number; // Sequential: Module 1, Module 2, etc.
    sessionType: TimingType; // The type label (Day, Week, Session, Module)
    sessionNumber: number; // The number for that type (Day 1, Week 2, etc.)
    deliveryType: DeliveryType;
    location: string;
    facilitatorId: string;
    facilitatorName: string;
    facilitatorEmail: string;
    contentIds: string[];
    estimatedDuration: number; // in minutes
}

export default function NewCurriculumCoursePage() {
    const router = useRouter();
    const firestore = useUsersFirestore();
    const { user } = useUser();

    const [formData, setFormData] = useState({
        title: '',
        description: '',
        cohortId: '',
        programId: '',
        defaultSessionType: 'Session' as TimingType, // Default session type for new modules
        status: 'Draft' as 'Draft' | 'Active' | 'Completed' | 'Archived',
        isPublished: false,
        isSelfPaced: false,
        allowSkipUnits: false,
    });

    const [modules, setModules] = useState<ModuleDraft[]>([]);
    const [expandedModules, setExpandedModules] = useState<Set<string>>(new Set());
    const [saving, setSaving] = useState(false);
    const [showContentPicker, setShowContentPicker] = useState<string | null>(null);

    // Fetch cohorts
    const cohortsQuery = useMemo(() => {
        if (!firestore) return null;
        return query(collection(firestore, 'cohorts'));
    }, [firestore]);
    const { data: cohorts } = useCollection<Cohort>(cohortsQuery as any);

    // Fetch programs
    const programsQuery = useMemo(() => {
        if (!firestore) return null;
        return query(collection(firestore, 'programs'));
    }, [firestore]);
    const { data: programs } = useCollection<Program>(programsQuery as any);

    // Fetch facilitators
    const facilitatorsQuery = useMemo(() => {
        if (!firestore) return null;
        return query(collection(firestore, 'users'), where('role', '==', 'Facilitator'));
    }, [firestore]);
    const { data: facilitators } = useCollection<User>(facilitatorsQuery as any);

    // Fetch content library
    const contentQuery = useMemo(() => {
        if (!firestore) return null;
        return query(collection(firestore, 'contentLibrary'), where('status', '==', 'published'));
    }, [firestore]);
    const { data: contentItems } = useCollection<ContentItem>(contentQuery as any);

    // Get selected cohort and program for display
    const selectedCohort = cohorts?.find(c => c.id === formData.cohortId);
    const selectedProgram = programs?.find(p => p.id === formData.programId);

    // Auto-generate course title from Program + Cohort/Intake
    const autoGeneratedTitle = useMemo(() => {
        if (selectedProgram && selectedCohort) {
            return `${selectedProgram.programName || selectedProgram.title} - ${selectedCohort.name}`;
        }
        return '';
    }, [selectedProgram, selectedCohort]);

    // Add a new module
    const addModule = () => {
        const moduleNumber = modules.length + 1;
        const newModule: ModuleDraft = {
            id: `temp_${Date.now()}`,
            title: '',
            description: '',
            moduleNumber,
            sessionType: formData.defaultSessionType,
            sessionNumber: moduleNumber, // Default to same as module number
            deliveryType: 'Virtual',
            location: '',
            facilitatorId: '',
            facilitatorName: '',
            facilitatorEmail: '',
            contentIds: [],
            estimatedDuration: 60,
        };
        setModules([...modules, newModule]);
        setExpandedModules(prev => new Set([...prev, newModule.id]));
    };

    // Remove a module
    const removeModule = (moduleId: string) => {
        const updatedModules = modules.filter(m => m.id !== moduleId);
        // Renumber remaining modules
        const renumberedModules = updatedModules.map((m, index) => ({
            ...m,
            moduleNumber: index + 1,
        }));
        setModules(renumberedModules);
        setExpandedModules(prev => {
            const next = new Set(prev);
            next.delete(moduleId);
            return next;
        });
    };

    // Update a module
    const updateModule = (moduleId: string, updates: Partial<ModuleDraft>) => {
        setModules(modules.map(m => m.id === moduleId ? { ...m, ...updates } : m));
    };

    // Toggle module expansion
    const toggleModuleExpansion = (moduleId: string) => {
        setExpandedModules(prev => {
            const next = new Set(prev);
            if (next.has(moduleId)) {
                next.delete(moduleId);
            } else {
                next.add(moduleId);
            }
            return next;
        });
    };

    // Add content to module
    const addContentToModule = (moduleId: string, contentId: string) => {
        const module = modules.find(m => m.id === moduleId);
        if (module && !module.contentIds.includes(contentId)) {
            updateModule(moduleId, { contentIds: [...module.contentIds, contentId] });
        }
    };

    // Remove content from module
    const removeContentFromModule = (moduleId: string, contentId: string) => {
        const module = modules.find(m => m.id === moduleId);
        if (module) {
            updateModule(moduleId, { contentIds: module.contentIds.filter(id => id !== contentId) });
        }
    };

    // Get delivery type icon
    const getDeliveryTypeIcon = (type: DeliveryType) => {
        switch (type) {
            case 'Virtual': return <Monitor className="h-4 w-4 text-blue-500" />;
            case 'Physical': return <MapPin className="h-4 w-4 text-green-500" />;
            case 'Hybrid': return <Laptop className="h-4 w-4 text-purple-500" />;
            case 'Self-paced': return <Video className="h-4 w-4 text-orange-500" />;
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!firestore || !user) return;

        if (!formData.programId || !formData.cohortId) {
            alert('Please select both Program and Cohort/Intake to auto-generate the course name');
            return;
        }

        try {
            setSaving(true);

            // Create the course first
            const courseId = await createLearningCourse(firestore, {
                title: autoGeneratedTitle || formData.title,
                description: formData.description,
                programId: formData.programId,
                programTitle: selectedProgram?.programName || selectedProgram?.title || '',
                cohortId: formData.cohortId || '',
                cohortName: formData.cohortId ? selectedCohort?.name : '',
                totalWeeks: modules.length || 1,
                moduleIds: [],
                status: formData.status,
                isPublished: formData.isPublished,
                isSelfPaced: formData.isSelfPaced,
                allowSkipUnits: formData.allowSkipUnits,
                createdBy: user.id,
            });

            // Create modules
            for (let i = 0; i < modules.length; i++) {
                const module = modules[i];
                await createLearningUnit(firestore, {
                    courseId,
                    title: module.title || `Module ${module.moduleNumber}`,
                    description: module.description,
                    orderIndex: i,
                    timingType: module.sessionType,
                    timingNumber: module.sessionNumber,
                    weekNumber: module.sessionNumber, // For backwards compatibility
                    deliveryType: module.deliveryType,
                    location: module.location,
                    facilitatorId: module.facilitatorId || undefined,
                    facilitatorName: module.facilitatorName || undefined,
                    facilitatorEmail: module.facilitatorEmail || undefined,
                    contentIds: module.contentIds,
                    estimatedDuration: module.estimatedDuration,
                    status: 'Draft',
                    isRequired: true,
                    createdBy: user.id,
                });
            }

            router.push(`/f/curriculum/${courseId}`);
        } catch (error) {
            console.error('Error creating course:', error);
            alert('Failed to create course');
        } finally {
            setSaving(false);
        }
    };

    return (
        <div className="w-full min-h-screen bg-gray-50/50 p-2 md:p-4 font-body">
            <div className="max-w-5xl mx-auto">
                {/* Header */}
                <div className="flex items-center gap-4 mb-6">
                    <Button
                        variant="ghost"
                        size="sm"
                        asChild
                        className="rounded-tl-lg rounded-br-lg"
                    >
                        <Link href="/f/curriculum">
                            <ArrowLeft className="h-4 w-4 mr-2" />
                            Back
                        </Link>
                    </Button>
                    <h1 className="text-3xl font-bold text-primary">Create Curriculum Course</h1>
                </div>

                <form onSubmit={handleSubmit} className="space-y-6">
                    {/* Course Details */}
                    <Card className="border-primary/10 shadow-lg rounded-tl-2xl rounded-br-2xl rounded-tr-none rounded-bl-none">
                        <CardHeader className="border-b border-primary/10 bg-primary/5">
                            <CardTitle className="text-primary">Course Details</CardTitle>
                            <CardDescription>Basic information about this learning course</CardDescription>
                        </CardHeader>
                        <CardContent className="p-6 space-y-4">
                            {/* Auto-generated Title Display */}
                            {autoGeneratedTitle && (
                                <div className="space-y-2 bg-blue-50 p-4 rounded-lg border border-blue-200">
                                    <Label className="text-primary font-bold text-xs uppercase tracking-widest">
                                        Course Name (Auto-Generated)
                                    </Label>
                                    <p className="text-lg font-bold text-primary">{autoGeneratedTitle}</p>
                                    <p className="text-xs text-primary/60">This name is automatically created from the selected Program and Intake/Cohort</p>
                                </div>
                            )}

                            {/* Description */}
                            <div className="space-y-2">
                                <Label htmlFor="description" className="text-primary font-bold text-xs uppercase tracking-widest">
                                    Description
                                </Label>
                                <Textarea
                                    id="description"
                                    value={formData.description}
                                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                                    placeholder="Brief description of the course..."
                                    className="border-primary/20 rounded-tl-lg rounded-br-lg"
                                    rows={3}
                                />
                            </div>

                            {/* Program and Cohort Row */}
                            <div className="grid grid-cols-2 gap-4">
                                {/* Cohort/Intake */}
                                <div className="space-y-2">
                                    <Label htmlFor="cohort" className="text-primary font-bold text-xs uppercase tracking-widest">
                                        Intake/Cohort *
                                    </Label>
                                    <Select
                                        value={formData.cohortId || 'none'}
                                        onValueChange={(value) => setFormData({ ...formData, cohortId: value === 'none' ? '' : value, programId: '' })}
                                        required
                                    >
                                        <SelectTrigger className="border-primary/20 rounded-tl-lg rounded-br-lg">
                                            <SelectValue placeholder="Select an intake/cohort" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {cohorts?.map((cohort) => (
                                                <SelectItem key={cohort.id} value={cohort.id}>
                                                    {cohort.name}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                    <p className="text-xs text-primary/60">Choose the cohort/intake first</p>
                                </div>

                                {/* Program */}
                                <div className="space-y-2">
                                    <Label htmlFor="program" className="text-primary font-bold text-xs uppercase tracking-widest">
                                        Program *
                                    </Label>
                                    <Select
                                        value={formData.programId || 'none'}
                                        onValueChange={(value) => setFormData({ ...formData, programId: value === 'none' ? '' : value })}
                                        required
                                        disabled={!formData.cohortId}
                                    >
                                        <SelectTrigger className="border-primary/20 rounded-tl-lg rounded-br-lg">
                                            <SelectValue placeholder={formData.cohortId ? "Select a program" : "Select a cohort first"} />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {programs?.filter(p => {
                                                if (!selectedCohort) return false;
                                                const cohortProgramIds = selectedCohort.programIds || (selectedCohort.programId ? [selectedCohort.programId] : []);
                                                return cohortProgramIds.includes(p.id);
                                            }).map((program, i) => (
                                                <SelectItem key={`${program.id}-${i}`} value={program.id}>
                                                    {program.programName || program.title} ({program.programType})
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                    <p className="text-xs text-primary/60">Course name will be: Program - Intake</p>
                                </div>
                            </div>

                            {/* Status and Settings Row */}
                            <div className="grid grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <Label className="text-primary font-bold text-xs uppercase tracking-widest">
                                        Status
                                    </Label>
                                    <Select value={formData.status} onValueChange={(value: any) => setFormData({ ...formData, status: value })}>
                                        <SelectTrigger className="border-primary/20 rounded-tl-lg rounded-br-lg">
                                            <SelectValue />
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="Draft">Draft</SelectItem>
                                            <SelectItem value="Active">Active</SelectItem>
                                            <SelectItem value="Completed">Completed</SelectItem>
                                            <SelectItem value="Archived">Archived</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </div>

                                <div className="space-y-2">
                                    <Label className="text-primary font-bold text-xs uppercase tracking-widest">
                                        Default Session Type
                                    </Label>
                                    <Select
                                        value={formData.defaultSessionType}
                                        onValueChange={(value: TimingType) => setFormData({ ...formData, defaultSessionType: value })}
                                    >
                                        <SelectTrigger className="border-primary/20 rounded-tl-lg rounded-br-lg">
                                            <SelectValue />
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="Session">Session</SelectItem>
                                            <SelectItem value="Day">Day</SelectItem>
                                            <SelectItem value="Week">Week</SelectItem>
                                            <SelectItem value="Module">Module</SelectItem>
                                        </SelectContent>
                                    </Select>
                                    <p className="text-xs text-gray-500">Used as default for new modules</p>
                                </div>
                            </div>

                            {/* Curriculum Settings */}
                            <div className="pt-2">
                                <Label className="text-primary font-bold text-xs uppercase tracking-widest mb-3 block">
                                    Curriculum Settings
                                </Label>
                                <div className="flex gap-6">
                                    <label className="flex items-center gap-2 text-sm cursor-pointer">
                                        <input
                                            type="checkbox"
                                            checked={formData.isSelfPaced}
                                            onChange={(e) => setFormData({ ...formData, isSelfPaced: e.target.checked })}
                                            className="rounded"
                                        />
                                        Self-paced learning
                                    </label>
                                    <label className="flex items-center gap-2 text-sm cursor-pointer">
                                        <input
                                            type="checkbox"
                                            checked={formData.allowSkipUnits}
                                            onChange={(e) => setFormData({ ...formData, allowSkipUnits: e.target.checked })}
                                            className="rounded"
                                        />
                                        Allow skipping modules
                                    </label>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Modules Section */}
                    <Card className="border-primary/10 shadow-lg rounded-tl-2xl rounded-br-2xl rounded-tr-none rounded-bl-none">
                        <CardHeader className="border-b border-primary/10 bg-primary/5">
                            <div className="flex justify-between items-center">
                                <div>
                                    <CardTitle className="text-primary">Course Modules</CardTitle>
                                    <CardDescription>Add modules with content, instructors, and session details</CardDescription>
                                </div>
                                <Button
                                    type="button"
                                    onClick={addModule}
                                    className="bg-accent hover:bg-accent/90 text-white rounded-tl-lg rounded-br-lg"
                                >
                                    <Plus className="h-4 w-4 mr-2" />
                                    Add Module
                                </Button>
                            </div>
                        </CardHeader>
                        <CardContent className="p-6">
                            {modules.length === 0 ? (
                                <div className="text-center py-12 bg-gray-50 rounded-lg border-2 border-dashed border-gray-200">
                                    <FileText className="h-12 w-12 mx-auto text-gray-300 mb-3" />
                                    <p className="text-gray-500 mb-4">No modules added yet</p>
                                    <Button
                                        type="button"
                                        onClick={addModule}
                                        variant="outline"
                                        className="rounded-tl-lg rounded-br-lg"
                                    >
                                        <Plus className="h-4 w-4 mr-2" />
                                        Add First Module
                                    </Button>
                                </div>
                            ) : (
                                <div className="space-y-4">
                                    {modules.map((module) => (
                                        <Card key={module.id} className="border-primary/10">
                                            {/* Module Header - Always Visible */}
                                            <div
                                                className="p-4 flex items-center gap-4 cursor-pointer hover:bg-gray-50"
                                                onClick={() => toggleModuleExpansion(module.id)}
                                            >
                                                <div className="flex-shrink-0">
                                                    <div className="h-10 w-10 flex items-center justify-center rounded-full bg-primary text-white font-bold">
                                                        {module.moduleNumber}
                                                    </div>
                                                </div>
                                                <div className="flex-1 min-w-0">
                                                    <div className="flex items-center gap-2 flex-wrap">
                                                        <Badge variant="outline" className="text-xs bg-primary/5">
                                                            Module {module.moduleNumber}
                                                        </Badge>
                                                        <Badge variant="outline" className="text-xs">
                                                            {module.sessionType} {module.sessionNumber}
                                                        </Badge>
                                                        {module.deliveryType && (
                                                            <Badge variant="outline" className="text-xs flex items-center gap-1">
                                                                {getDeliveryTypeIcon(module.deliveryType)}
                                                                {module.deliveryType}
                                                            </Badge>
                                                        )}
                                                        {module.facilitatorName && (
                                                            <Badge variant="outline" className="text-xs bg-green-50 text-green-700">
                                                                {module.facilitatorName}
                                                            </Badge>
                                                        )}
                                                        {module.contentIds.length > 0 && (
                                                            <Badge variant="outline" className="text-xs bg-blue-50 text-blue-700">
                                                                {module.contentIds.length} materials
                                                            </Badge>
                                                        )}
                                                    </div>
                                                    <p className="font-medium text-primary truncate mt-1">
                                                        {module.title || `Module ${module.moduleNumber}`}
                                                    </p>
                                                </div>
                                                <Button
                                                    type="button"
                                                    variant="ghost"
                                                    size="sm"
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        removeModule(module.id);
                                                    }}
                                                    className="text-red-500 hover:text-red-600 hover:bg-red-50"
                                                >
                                                    <Trash2 className="h-4 w-4" />
                                                </Button>
                                                {expandedModules.has(module.id) ? (
                                                    <ChevronUp className="h-5 w-5 text-gray-400" />
                                                ) : (
                                                    <ChevronDown className="h-5 w-5 text-gray-400" />
                                                )}
                                            </div>

                                            {/* Module Details - Expandable */}
                                            {expandedModules.has(module.id) && (
                                                <CardContent className="border-t border-primary/10 p-4 space-y-4 bg-gray-50/50">
                                                    {/* Title Row */}
                                                    <div className="grid grid-cols-2 gap-4">
                                                        <div className="space-y-2">
                                                            <Label className="text-xs uppercase tracking-widest text-primary/60">
                                                                Module Title
                                                            </Label>
                                                            <Input
                                                                value={module.title}
                                                                onChange={(e) => updateModule(module.id, { title: e.target.value })}
                                                                placeholder={`Module ${module.moduleNumber} Title`}
                                                                className="border-primary/20 rounded-tl-lg rounded-br-lg bg-white"
                                                                onClick={(e) => e.stopPropagation()}
                                                            />
                                                        </div>
                                                        <div className="space-y-2">
                                                            <Label className="text-xs uppercase tracking-widest text-primary/60">
                                                                Duration (minutes)
                                                            </Label>
                                                            <Input
                                                                type="number"
                                                                min="1"
                                                                value={module.estimatedDuration}
                                                                onChange={(e) => updateModule(module.id, { estimatedDuration: parseInt(e.target.value) || 60 })}
                                                                className="border-primary/20 rounded-tl-lg rounded-br-lg bg-white"
                                                                onClick={(e) => e.stopPropagation()}
                                                            />
                                                        </div>
                                                    </div>

                                                    {/* Session Type and Delivery */}
                                                    <div className="grid grid-cols-4 gap-4">
                                                        <div className="space-y-2">
                                                            <Label className="text-xs uppercase tracking-widest text-primary/60">
                                                                Session Type
                                                            </Label>
                                                            <Select
                                                                value={module.sessionType}
                                                                onValueChange={(value: TimingType) => updateModule(module.id, { sessionType: value })}
                                                            >
                                                                <SelectTrigger className="border-primary/20 rounded-tl-lg rounded-br-lg bg-white">
                                                                    <SelectValue />
                                                                </SelectTrigger>
                                                                <SelectContent>
                                                                    <SelectItem value="Session">Session</SelectItem>
                                                                    <SelectItem value="Day">Day</SelectItem>
                                                                    <SelectItem value="Week">Week</SelectItem>
                                                                    <SelectItem value="Module">Module</SelectItem>
                                                                </SelectContent>
                                                            </Select>
                                                        </div>
                                                        <div className="space-y-2">
                                                            <Label className="text-xs uppercase tracking-widest text-primary/60">
                                                                {module.sessionType} #
                                                            </Label>
                                                            <Input
                                                                type="number"
                                                                min="1"
                                                                value={module.sessionNumber}
                                                                onChange={(e) => updateModule(module.id, { sessionNumber: parseInt(e.target.value) || 1 })}
                                                                className="border-primary/20 rounded-tl-lg rounded-br-lg bg-white"
                                                                onClick={(e) => e.stopPropagation()}
                                                            />
                                                        </div>
                                                        <div className="space-y-2">
                                                            <Label className="text-xs uppercase tracking-widest text-primary/60">
                                                                Delivery Type
                                                            </Label>
                                                            <Select
                                                                value={module.deliveryType}
                                                                onValueChange={(value: DeliveryType) => updateModule(module.id, { deliveryType: value })}
                                                            >
                                                                <SelectTrigger className="border-primary/20 rounded-tl-lg rounded-br-lg bg-white">
                                                                    <SelectValue />
                                                                </SelectTrigger>
                                                                <SelectContent>
                                                                    <SelectItem value="Virtual">Virtual</SelectItem>
                                                                    <SelectItem value="Physical">Physical</SelectItem>
                                                                    <SelectItem value="Hybrid">Hybrid</SelectItem>
                                                                    <SelectItem value="Self-paced">Self-paced</SelectItem>
                                                                </SelectContent>
                                                            </Select>
                                                        </div>
                                                        {(module.deliveryType === 'Physical' || module.deliveryType === 'Hybrid') && (
                                                            <div className="space-y-2">
                                                                <Label className="text-xs uppercase tracking-widest text-primary/60">
                                                                    Location
                                                                </Label>
                                                                <Input
                                                                    value={module.location}
                                                                    onChange={(e) => updateModule(module.id, { location: e.target.value })}
                                                                    placeholder="Room/Venue"
                                                                    className="border-primary/20 rounded-tl-lg rounded-br-lg bg-white"
                                                                    onClick={(e) => e.stopPropagation()}
                                                                />
                                                            </div>
                                                        )}
                                                    </div>

                                                    {/* Instructor */}
                                                    <div className="space-y-2">
                                                        <Label className="text-xs uppercase tracking-widest text-primary/60">
                                                            Instructor / Facilitator
                                                        </Label>
                                                        <Select
                                                            value={module.facilitatorId || 'none'}
                                                            onValueChange={(value) => {
                                                                const facilitator = facilitators?.find(f => f.id === value);
                                                                updateModule(module.id, {
                                                                    facilitatorId: value === 'none' ? '' : value,
                                                                    facilitatorName: facilitator?.name || '',
                                                                    facilitatorEmail: facilitator?.email || '',
                                                                });
                                                            }}
                                                        >
                                                            <SelectTrigger className="border-primary/20 rounded-tl-lg rounded-br-lg bg-white">
                                                                <SelectValue placeholder="Select instructor" />
                                                            </SelectTrigger>
                                                            <SelectContent>
                                                                <SelectItem value="none">No instructor assigned</SelectItem>
                                                                {facilitators?.map((f) => (
                                                                    <SelectItem key={f.id} value={f.id}>
                                                                        {f.name} ({f.email})
                                                                    </SelectItem>
                                                                ))}
                                                            </SelectContent>
                                                        </Select>
                                                    </div>

                                                    {/* Content Library */}
                                                    <div className="space-y-2">
                                                        <div className="flex justify-between items-center">
                                                            <Label className="text-xs uppercase tracking-widest text-primary/60">
                                                                Content / Materials
                                                            </Label>
                                                            <Button
                                                                type="button"
                                                                variant="outline"
                                                                size="sm"
                                                                onClick={(e) => {
                                                                    e.stopPropagation();
                                                                    setShowContentPicker(showContentPicker === module.id ? null : module.id);
                                                                }}
                                                                className="rounded-tl-md rounded-br-md text-xs"
                                                            >
                                                                <Plus className="h-3 w-3 mr-1" />
                                                                Add Content
                                                            </Button>
                                                        </div>

                                                        {/* Selected Content */}
                                                        {module.contentIds.length > 0 && (
                                                            <div className="flex flex-wrap gap-2">
                                                                {module.contentIds.map(contentId => {
                                                                    const content = contentItems?.find(c => c.id === contentId);
                                                                    return (
                                                                        <Badge
                                                                            key={contentId}
                                                                            variant="secondary"
                                                                            className="flex items-center gap-1 pr-1"
                                                                        >
                                                                            {content?.type === 'video' && <Video className="h-3 w-3" />}
                                                                            {content?.type === 'document' && <FileText className="h-3 w-3" />}
                                                                            {content?.title || contentId}
                                                                            <button
                                                                                type="button"
                                                                                onClick={(e) => {
                                                                                    e.stopPropagation();
                                                                                    removeContentFromModule(module.id, contentId);
                                                                                }}
                                                                                className="ml-1 hover:bg-gray-300 rounded-full p-0.5"
                                                                            >
                                                                                <X className="h-3 w-3" />
                                                                            </button>
                                                                        </Badge>
                                                                    );
                                                                })}
                                                            </div>
                                                        )}

                                                        {/* Content Picker */}
                                                        {showContentPicker === module.id && (
                                                            <div className="border rounded-lg p-3 bg-white max-h-48 overflow-y-auto">
                                                                {contentItems && contentItems.length > 0 ? (
                                                                    <div className="space-y-1">
                                                                        {contentItems
                                                                            .filter(c => !module.contentIds.includes(c.id))
                                                                            .map(content => (
                                                                                <div
                                                                                    key={content.id}
                                                                                    className="flex items-center justify-between p-2 hover:bg-gray-50 rounded cursor-pointer"
                                                                                    onClick={(e) => {
                                                                                        e.stopPropagation();
                                                                                        addContentToModule(module.id, content.id);
                                                                                    }}
                                                                                >
                                                                                    <div className="flex items-center gap-2">
                                                                                        {content.type === 'video' && <Video className="h-4 w-4 text-purple-500" />}
                                                                                        {content.type === 'document' && <FileText className="h-4 w-4 text-blue-500" />}
                                                                                        <span className="text-sm">{content.title}</span>
                                                                                    </div>
                                                                                    <Plus className="h-4 w-4 text-green-500" />
                                                                                </div>
                                                                            ))}
                                                                        {contentItems.filter(c => !module.contentIds.includes(c.id)).length === 0 && (
                                                                            <p className="text-sm text-gray-500 text-center py-2">All content already added</p>
                                                                        )}
                                                                    </div>
                                                                ) : (
                                                                    <p className="text-sm text-gray-500 text-center py-4">
                                                                        No published content available
                                                                    </p>
                                                                )}
                                                            </div>
                                                        )}
                                                    </div>

                                                    {/* Description */}
                                                    <div className="space-y-2">
                                                        <Label className="text-xs uppercase tracking-widest text-primary/60">
                                                            Description (Optional)
                                                        </Label>
                                                        <Textarea
                                                            value={module.description}
                                                            onChange={(e) => updateModule(module.id, { description: e.target.value })}
                                                            placeholder="What will learners cover in this module?"
                                                            className="border-primary/20 rounded-tl-lg rounded-br-lg bg-white"
                                                            rows={2}
                                                            onClick={(e) => e.stopPropagation()}
                                                        />
                                                    </div>
                                                </CardContent>
                                            )}
                                        </Card>
                                    ))}
                                </div>
                            )}
                        </CardContent>
                    </Card>

                    {/* Actions */}
                    <div className="flex justify-end gap-4">
                        <Button
                            type="button"
                            variant="outline"
                            onClick={() => router.push('/f/curriculum')}
                            className="rounded-tl-lg rounded-br-lg"
                        >
                            Cancel
                        </Button>
                        <Button
                            type="submit"
                            disabled={saving}
                            className="bg-accent hover:bg-accent/90 text-white rounded-tl-lg rounded-br-lg min-w-[150px]"
                        >
                            {saving ? (
                                <>
                                    <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                                    Creating...
                                </>
                            ) : (
                                <>
                                    <Save className="h-4 w-4 mr-2" />
                                    Create Course
                                </>
                            )}
                        </Button>
                    </div>
                </form>
            </div>
        </div>
    );
}
